# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seniordesign.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='seniordesign.proto',
  package='seniordesign',
  syntax='proto3',
  serialized_pb=b'\n\x12seniordesign.proto\x12\x0cseniordesign\"S\n\x11ProcessingResults\x12*\n\tdirection\x18\x01 \x01(\x0e\x32\x17.seniordesign.Direction\x12\x12\n\nconfidence\x18\x02 \x01(\x01\"\"\n\rProcessingAck\x12\x11\n\ttimestamp\x18\x01 \x01(\x04*H\n\tDirection\x12\x0b\n\x07NEUTRAL\x10\x00\x12\x0b\n\x07\x46ORWARD\x10\x01\x12\x0c\n\x08\x42\x41\x43KWARD\x10\x02\x12\x08\n\x04LEFT\x10\x03\x12\t\n\x05RIGHT\x10\x04\x62\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='seniordesign.Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEUTRAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORWARD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKWARD', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=157,
  serialized_end=229,
)
_sym_db.RegisterEnumDescriptor(_DIRECTION)

Direction = enum_type_wrapper.EnumTypeWrapper(_DIRECTION)
NEUTRAL = 0
FORWARD = 1
BACKWARD = 2
LEFT = 3
RIGHT = 4



_PROCESSINGRESULTS = _descriptor.Descriptor(
  name='ProcessingResults',
  full_name='seniordesign.ProcessingResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='seniordesign.ProcessingResults.direction', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='seniordesign.ProcessingResults.confidence', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=119,
)


_PROCESSINGACK = _descriptor.Descriptor(
  name='ProcessingAck',
  full_name='seniordesign.ProcessingAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='seniordesign.ProcessingAck.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=155,
)

_PROCESSINGRESULTS.fields_by_name['direction'].enum_type = _DIRECTION
DESCRIPTOR.message_types_by_name['ProcessingResults'] = _PROCESSINGRESULTS
DESCRIPTOR.message_types_by_name['ProcessingAck'] = _PROCESSINGACK
DESCRIPTOR.enum_types_by_name['Direction'] = _DIRECTION

ProcessingResults = _reflection.GeneratedProtocolMessageType('ProcessingResults', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSINGRESULTS,
  __module__ = 'seniordesign_pb2'
  # @@protoc_insertion_point(class_scope:seniordesign.ProcessingResults)
  ))
_sym_db.RegisterMessage(ProcessingResults)

ProcessingAck = _reflection.GeneratedProtocolMessageType('ProcessingAck', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSINGACK,
  __module__ = 'seniordesign_pb2'
  # @@protoc_insertion_point(class_scope:seniordesign.ProcessingAck)
  ))
_sym_db.RegisterMessage(ProcessingAck)


# @@protoc_insertion_point(module_scope)
